routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'ConferenceController@index');

Route::resource('conferences', 'ConferenceController')->only(['index', 'show']);
Route::resource('user_conferences', 'UserConferenceController')->only(['index', 'store']);
Route::get('/session_conference', 'UserConferenceController@session_conference');

Auth::routes(['verify' => true, 'register' => false]);

Route::get('/admin', 'AdminController@index')->name('admin');

Route::get('/export', 'ExcelController@export');

app/Models/Conference.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Conference extends Model {
  public function views () {
    return $this->hasMany(ViewConference::class);
  }
}

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

app/Models/UserConference.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class UserConference extends Model {
  public function views () {
    return $this->hasMany(ViewConference::class);
  }
}

app/Models/ViewConference.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class ViewConference extends Model {
  public function user () {
    return $this->belongsTo(UserConference::class, 'user_conference_id');
  }

  public function conference () {
    return $this->belongsTo(Conference::class, 'conference_id');
  }
}

app/Http/Controllers/AdminController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\UserConference;
use App\Models\Conference;


class AdminController extends Controller {

  /**
   * Create a new controller instance. 
   */
  public function __construct() {
    $this->middleware('auth');
  }

  /**
   * Show the application dashboard. 
   */
  public function index() {
    $users = UserConference::all();
    $conferences = Conference::all();

    return view('admin', compact('users', 'conferences'));
  }
}

app/Http/Controllers/ConferenceController.php
<?php

namespace App\Http\Controllers;

use App\Models\Conference;
use App\Models\ViewConference;
use App\Models\UserConference;
use Illuminate\Http\Request;
use Cookie;

class ConferenceController extends Controller {

  /**
   * Display a listing of the resource. 
   */
  public function index() {
    $conferences = Conference::all();
  
    return view('conferences.index', compact('conferences'));
  }


  /**
   * Display the specified resource. 
   */
  public function show($id) {
    $conference = Conference::find($id);

    if (Cookie::has('user_logged')) {
      $user = UserConference::where('email', '=', Cookie::get('user_logged'))->first();

      $view = new ViewConference();
      $view->user_conference_id = $user->id;
      $view->conference_id = $id;
      $view->save();
      
      return view('conferences.show', compact('conference'));
    } else {
      return view('users.index');
    }
    
    
  }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController {
  use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/ExcelController.php
<?php

namespace App\Http\Controllers;

use App\Exports\ReportExport;
use Illuminate\Http\Request;
use Maatwebsite\Excel\Facades\Excel;

class ExcelController extends Controller {

  public function export() {
    return Excel::download(new ReportExport, 'report.xlsx');
  }

}

app/Http/Controllers/UserConferenceController.php
<?php

namespace App\Http\Controllers;

use App\Models\UserConference;
use Illuminate\Http\Request;
use Cookie;
use Session;

class UserConferenceController extends Controller {
  /**
   * Display a listing of the resource. 
   */
  public function index() {
    return view('user_conferences.index');
  }

  /**
   * Store a newly created resource in storage. 
   */
  public function store(Request $request) {
    $this->validate($request, array(
      'name' => 'required',
      'lastname' => 'required',
      'company' => 'required',
      'email' => 'required|email|unique:user_conferences,email',
      'position' => 'required',
      'address' => 'required',
      'city' => 'required',
      'phone' => 'required'
    ));

    $user = new UserConference();
    $user->name = $request->input('name');
    $user->lastname = $request->input('lastname');
    $user->company = $request->input('company');
    $user->email = $request->input('email');
    $user->position = $request->input('position');
    $user->address = $request->input('address');
    $user->city = $request->input('city');
    $user->phone = $request->input('phone');
    $user->save();

    Session::flash('messages','El usuario ha sido creado.');
    Session::flash('class', 'alert-success'); 

    return back()->withInput();
  }

  /**
   * Method for logged users
   */
  public function session_conference(Request $request) {

    $this->validate($request, array(
      'email' => 'required|email',
    ));

    $user = UserConference::where('email', '=', $request->get('email'))->first();

    if ($user != null) {
      Cookie::queue('user_logged', $user->email, 2);
    } else {
      Session::flash('messages','Este correo aun no se ha registrado.');
      Session::flash('class', 'alert-warning'); 
    }
    return back()->withInput();
  }
}

resources/views/admin.blade.php
@extends('layouts.app')

@section('title', 'Administrador')

@section('content')
  <h2 class="description">Hola Administrador, 
    <a href="{{ route('logout') }}" onclick="event.preventDefault(); document.getElementById('logout-form').submit();">
      {{ __('Cerrar Sesión') }}
    </a>
    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
      @csrf
    </form>
  </h2>

  @if (session('status'))
  <div class="alert alert-success" role="alert">
    {{ session('status') }}
  </div>
  @endif

  <h3 class="main-title">Reporte de vistas de videos por usuario.</h3>

  @foreach($users as $user)
    <div>
      <h3 class="subtitle">{{$user->name}} ha visto {{$user->views->count()}} conferencias</h3>
      <ul>
          @foreach($conferences as $conference)
            @php
              $viewsByConference = 0
            @endphp
            @foreach($user->views as $view)
              @if ($view->conference->id == $conference->id)
                @php
                  $viewsByConference++
                @endphp
              @endif
            @endforeach
            <li>Conferencia de {{$conference->title}} fue vista {{$viewsByConference}} veces</li>
          @endforeach  
      </ul>
    </div>
  @endforeach
  <a href="/export" class="btn btn-red">Exportar reporte en Excel</a>

@endsection

resources/views/conferences/index.blade.php
@extends('layouts.app')

@section('title', 'Bienvenidos')

@section('content')
  <h2 class="description">Haz clic para entrar a cualquiera  de nuestras conferencias en directo.</h2>
  <div class="conferences">
    <div class="row justify-content-center">
      @foreach($conferences as $conference)
        <div class="col-lg-4 col-md-6 col-sm-12">
          <div class="conference-item">
            <a href="/conferences/{{$conference->id}}">
              <h3 class="title">{{$conference->title}}</h3>
              <img src="http://i3.ytimg.com/vi/{{$conference->id_video}}/hqdefault.jpg" alt="{{$conference->title}}" class="image" />
              <div class="play-icon"></div>
            </a>
          </div>
        </div>
      @endforeach
    </div>
  </div>

@endsection

resources/views/conferences/show.blade.php
@extends('layouts.app')

@section('title', $conference->title)

@section('content')
  <div class="row">
    <div class="col-xl-6 offset-xl-3 col-lg-8 offset-lg-2 col-md-10 offset-md-1">
      <div class="conference-single">
        <h2 class="title">{{$conference->title}}</h2>
        <div class="video">
          <iframe width="560" height="315" src="https://www.youtube.com/embed/{{$conference->id_video}}?autoplay=1" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
        </div>
      </div>
    </div>
    <div class="col-md-4 offset-md-8">
      <a href="{{ url('/') }}" class="btn btn-red btn-block">Regresa al menu</a>
    </div>
  </div>
@endsection

resources/views/exports/report.blade.php
<table>
  <thead>
  <tr>
    <th>ID</th>
    <th>Usuario</th>
    <th>Conferencias vistas</th>
    @foreach($conferences as $conference)
      <th>{{$conference->title}}</th>
    @endforeach
  </tr>
  </thead>
  <tbody>
    @foreach($users as $user)
      <tr>
          <td>{{ $user->id }}</td>
          <td>{{ $user->name }}</td>
          <td>{{ $user->views->count() }}</td>
          @foreach($conferences as $conference)
            @php
              $viewsByConference = 0
            @endphp
            @foreach($user->views as $view)
              @if ($view->conference->id == $conference->id)
                @php
                  $viewsByConference++
                @endphp
              @endif
            @endforeach
            <td>{{$viewsByConference}}</td>
          @endforeach  
      </tr>
    @endforeach
  </tbody>
</table>

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
	<meta charset="UTF-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1" />
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <title>Conferences Laravel - @yield('title')</title>
	<link rel="stylesheet" href="{{ asset('css/app.css') }}" />
</head>
<body>
  <section id="wrapper-header">
    <div class="container">
      <div class="row">
        <div class="col-md-6">
          <div class="logo">
            <span class="main">
              Oracle
            </span>
            Digital <b>Transformation</b> Day
          </div>
        </div>
        <div class="col-md-6">
          <h1 class="main-title">@yield('title')</h1>
        </div>
      </div>
    </div>
  </section>
  <section id="wrapper-content">
  	<div class="container">
  		@yield('content')
  	</div>
  </section>
  <section id="wrapper-footer">
    <div class="container">
      #OracleDigital
    </div>
  </section>
	<script type="text/javascript" src="{{ asset('js/app.js') }}"></script>
</body>
</html>

resources/views/users/index.blade.php
@extends('layouts.app')

@section('title', 'Regístrate')

@section('content')
  <div class="row">
    <div class="col-lg-7 offset-lg-5 col-md-8 offset-md-4">
      <div class="row">
        <div class="col-md-12">
          @if ($errors->any())
            <div class="alert alert-danger">
              <ul>
                @foreach ($errors->all() as $error)
                  <li>{{ $error }}</li>
                @endforeach
              </ul>
            </div>
          @endif

          @if (Session::has('messages'))
            <div class="alert {{ Session::get('class') }}">
              {{ Session::get('messages') }}
            </div>
          @endif
          <form class="form-group form-users" id="register-form" method="POST" action="{{ route('user_conferences.store') }}">
            @csrf
            <div class="row">
              <div class="col-md-6">  
                <div class="form-group">
                  <input type="text" name="name" class="form-control" placeholder="Nombre." />
                </div>
                <div class="form-group">
                  <input type="text" name="company" class="form-control" placeholder="Empresa." />
                </div>
                <div class="form-group">
                  <input type="text" name="position" class="form-control" placeholder="Cargo." />
                </div>
                <div class="form-group">
                  <input type="text" name="city" class="form-control" placeholder="Ciudad." />
                </div>
                <a href="#" class="btn btn-red btn-block btn-login-inside" data-toggle="modal" data-target="#loginModal">Ingresa</a>
              </div>
              <div class="col-md-6">
                <div class="form-group">
                  <input type="text" name="lastname" class="form-control" placeholder="Apellido." />
                </div>
                <div class="form-group">
                  <input type="text" name="email" class="form-control" placeholder="e-mail." />
                </div>
                <div class="form-group">
                  <input type="text" name="address" class="form-control" placeholder="Dirección." />
                </div>
                <div class="form-group">
                  <input type="text" name="phone" class="form-control" placeholder="Teléfono." />
                </div>
                <button type="submit" class="btn btn-red btn-block">Regístrate</button>
              </div>
            </div>
          </form>
        </div>

        <div class="col-sm-12">
          <a href="#" class="btn btn-red btn-block btn-login-outside" data-toggle="modal" data-target="#loginModal">Ingresa</a>
        </div>

        <div class="col-md-6 offset-md-6 col-sm-12">
          <a href="{{ url('/') }}" class="btn btn-red btn-block">Regresa al menu</a>
        </div>
      </div>
    </div>
    <div class="modal fade" id="loginModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
      <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
          <div class="modal-body">
            <div class="row">
              <div class="col-md-12">              
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
                </button>
                <div class="description">Escribe tu correo electrónico para poder ingresar.</div>
                <form class="form-group" id="login-form"  method="GET" action="{{ action('UserConferenceController@session_conference') }}">
                  <div class="row">
                    <div class="col-md-12"> 
                      <div class="form-group">
                        <input type="text" name="email" class="form-control" />
                      </div>
                    </div>
                    <div class="col-md-8 offset-md-4">
                      <button type="submit" class="btn btn-red btn-block">Ingresa</button>
                    </div>
                  </div>
                </form>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
@endsection